version: '3'
services:
    kafka:
      image: wurstmeister/kafka
      container_name: kafka-wordcount
      ports:
        - "9092:9092"
      environment:
        KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
        KAFKA_ADVERTISED_PORT: 9092
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        HOSTNAME_COMMAND: hostname -i | awk '{print $$1}'
        KAFKA_HEAP_OPTS: -Xmx3G -Xms1G
        KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
        KAFKA_DELETE_TOPIC_ENABLE: "true"
        KAFKA_LISTENERS: PLAINTEXT://kafka:29092,EXTERNAL://_{HOSTNAME_COMMAND}:9092
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,EXTERNAL://localhost:9092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        KAFKA_DEFAULT_REPLICATION_FACTOR: 1
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
        KAFKA_LOG_RETENTION_MS: -1
        KAFKA_MESSAGE_MAX_BYTES: 10485880
        KAFKA_NUM_PARTITIONS: 8

      depends_on:
        - zookeeper
    zookeeper:
      image: wurstmeister/zookeeper
      ports:
        - "2181:2181"
      environment:
        - KAFKA_ADVERTISED_HOST_NAME=zookeeper

    schema-registry:
      image: confluentinc/cp-schema-registry:5.3.1
      ports:
        - "8081:8081"
      environment:
        SCHEMA_REGISTRY_HOST_NAME: schema-registry
        SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
        SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081
      depends_on:
        - kafka
    kowl:
      image: quay.io/cloudhut/kowl:v1.4.0
      restart: on-failure
      hostname: kowl
      volumes:
        - ./kowl-config.yaml:/etc/kowl/config.yaml
      ports:
        - "18080:8080"
      environment:
        KAFKA_SCHEMAREGISTRY_ENABLED: "true"
        KAFKA_SCHEMAREGISTRY_URLS: http://schema-registry:8081
      entrypoint: ./kowl --config.filepath=/etc/kowl/config.yaml
      depends_on:
        - schema-registry
        - kafka
